apiVersion: v1
kind: Service
metadata:
  name: fas-propriedades
  namespace: fiapk8s
spec:
  selector:
    app: fas-propriedades
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP

