# Prometheus - AgroSolutions/FAS
# Coleta m√©tricas das APIs .NET (endpoint /metrics)

global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'ingestion-api'
    static_configs:
      - targets: ['ingestion-api:8080']
    metrics_path: /metrics

  - job_name: 'fas-api-properties'
    static_configs:
      - targets: ['fas-api-properties:8080']
    metrics_path: /metrics

  - job_name: 'fas-api-users'
    static_configs:
      - targets: ['fas-api-users:8080']
    metrics_path: /metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: /metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
