apiVersion: v1
kind: Service
metadata:
  name: usuarios-svc
  namespace: fiapk8s
  labels:
    app: usuarios-api
spec:
  type: LoadBalancer
  selector:
    app: usuarios-api
  ports:
    - name: http
      port: 80
      targetPort: 8080
      protocol: TCP
